import type { Metadata } from 'next'
import { Roboto as FontSans, Roboto_Condensed as FontSansAlt, Montserrat } from 'next/font/google'

import { Toaster } from '@/components/ui/sonner'
import { SWRGlobalProvider } from '@/lib/api/swr-global-provider'
import { cn } from '@/lib/utils'
import { AuthServerProvider } from '@/providers/auth-server-provider'
import { CartStoreProvider } from '@/providers/cart-store-provider'
import '@/styles/globals.scss'
import { LoginDialog } from '@/components/LoginDialog'
import { LocationStoreProvider } from '@/providers/location-store-provider'

const fontSans = FontSans({
  weight: ['400', '500', '700'],
  subsets: ['latin', 'cyrillic'],
  style: ['normal', 'italic'],
  variable: '--font-sans',
  display: 'swap'
})

const fontSansAlt = FontSansAlt({
  weight: ['400', '500', '700'],
  subsets: ['latin', 'cyrillic'],
  style: ['normal', 'italic'],
  variable: '--font-sans-narrow',
  display: 'swap'
})

const fontMontserrat = Montserrat({
  weight: ['400', '500', '700', '900'],
  subsets: ['latin', 'cyrillic'],
  style: ['normal', 'italic'],
  variable: '--font-sans-wide',
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ru">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable,
          fontSansAlt.variable,
          fontMontserrat.variable
        )}
      >
        <SWRGlobalProvider>
          <AuthServerProvider>
            <LocationStoreProvider>
              <CartStoreProvider>{children}</CartStoreProvider>
            </LocationStoreProvider>
          </AuthServerProvider>
        </SWRGlobalProvider>
        <Toaster richColors position="top-center" />
      </body>
    </html>
  )
}
