import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1736507176353 implements MigrationInterface {
    name = 'Init1736507176353'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`option_value\` DROP FOREIGN KEY \`option_value_optionId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`option_value\` DROP FOREIGN KEY \`option_value_productId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`category\` DROP FOREIGN KEY \`category_imageId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`category\` DROP FOREIGN KEY \`category_parentId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`product_image\` DROP FOREIGN KEY \`product_image_fileId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`product_image\` DROP FOREIGN KEY \`product_image_productId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`offer\` DROP FOREIGN KEY \`offer_productId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`product\` DROP FOREIGN KEY \`product_brandId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`cart_product\` DROP FOREIGN KEY \`cart_product_cartId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`cart_product\` DROP FOREIGN KEY \`cart_product_productId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`cart\` DROP FOREIGN KEY \`cart_userId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP FOREIGN KEY \`user_roleId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`order_product\` DROP FOREIGN KEY \`order_product_orderId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`order_product\` DROP FOREIGN KEY \`order_product_productId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`delivery\` DROP FOREIGN KEY \`delivery_orderId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`order\` DROP FOREIGN KEY \`order_userId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`payment\` DROP FOREIGN KEY \`payment_orderId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`blog_post\` DROP FOREIGN KEY \`blog_post_imageId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`category_options\` DROP FOREIGN KEY \`category_options_categoryId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`category_options\` DROP FOREIGN KEY \`category_options_optionId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`offer_option_values\` DROP FOREIGN KEY \`offer_option_values_offerId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`offer_option_values\` DROP FOREIGN KEY \`offer_option_values_optionValueId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`category_products\` DROP FOREIGN KEY \`category_products_categoryId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`category_products\` DROP FOREIGN KEY \`category_products_productId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`cart_product_option_values\` DROP FOREIGN KEY \`cart_product_option_values_cartProductId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`cart_product_option_values\` DROP FOREIGN KEY \`cart_product_option_values_optionValueId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`blog_tag_posts\` DROP FOREIGN KEY \`blog_tag_posts_blogPostId_fkey\``);
        await queryRunner.query(`ALTER TABLE \`blog_tag_posts\` DROP FOREIGN KEY \`blog_tag_posts_blogTagId_fkey\``);
        await queryRunner.query(`DROP INDEX \`role_title_key\` ON \`role\``);
        await queryRunner.query(`DROP INDEX \`option_value_optionId_idx\` ON \`option_value\``);
        await queryRunner.query(`DROP INDEX \`option_value_productId_idx\` ON \`option_value\``);
        await queryRunner.query(`DROP INDEX \`option_key_key\` ON \`option\``);
        await queryRunner.query(`DROP INDEX \`category_alias_key\` ON \`category\``);
        await queryRunner.query(`DROP INDEX \`category_imageId_idx\` ON \`category\``);
        await queryRunner.query(`DROP INDEX \`category_parentId_idx\` ON \`category\``);
        await queryRunner.query(`DROP INDEX \`product_image_fileId_idx\` ON \`product_image\``);
        await queryRunner.query(`DROP INDEX \`product_image_productId_idx\` ON \`product_image\``);
        await queryRunner.query(`DROP INDEX \`offer_productId_idx\` ON \`offer\``);
        await queryRunner.query(`DROP INDEX \`product_alias_key\` ON \`product\``);
        await queryRunner.query(`DROP INDEX \`product_brandId_idx\` ON \`product\``);
        await queryRunner.query(`DROP INDEX \`cart_product_cartId_idx\` ON \`cart_product\``);
        await queryRunner.query(`DROP INDEX \`cart_product_productId_idx\` ON \`cart_product\``);
        await queryRunner.query(`DROP INDEX \`cart_userId_key\` ON \`cart\``);
        await queryRunner.query(`DROP INDEX \`user_email_key\` ON \`user\``);
        await queryRunner.query(`DROP INDEX \`user_roleId_idx\` ON \`user\``);
        await queryRunner.query(`DROP INDEX \`order_product_orderId_idx\` ON \`order_product\``);
        await queryRunner.query(`DROP INDEX \`order_product_productId_idx\` ON \`order_product\``);
        await queryRunner.query(`DROP INDEX \`delivery_orderId_key\` ON \`delivery\``);
        await queryRunner.query(`DROP INDEX \`order_hash_key\` ON \`order\``);
        await queryRunner.query(`DROP INDEX \`order_userId_idx\` ON \`order\``);
        await queryRunner.query(`DROP INDEX \`payment_orderId_key\` ON \`payment\``);
        await queryRunner.query(`DROP INDEX \`blog_tag_alias_key\` ON \`blog_tag\``);
        await queryRunner.query(`DROP INDEX \`blog_post_alias_key\` ON \`blog_post\``);
        await queryRunner.query(`DROP INDEX \`blog_post_imageId_idx\` ON \`blog_post\``);
        await queryRunner.query(`DROP INDEX \`category_options_categoryId_idx\` ON \`category_options\``);
        await queryRunner.query(`DROP INDEX \`category_options_optionId_idx\` ON \`category_options\``);
        await queryRunner.query(`DROP INDEX \`offer_option_values_offerId_idx\` ON \`offer_option_values\``);
        await queryRunner.query(`DROP INDEX \`offer_option_values_optionValueId_idx\` ON \`offer_option_values\``);
        await queryRunner.query(`DROP INDEX \`category_products_categoryId_idx\` ON \`category_products\``);
        await queryRunner.query(`DROP INDEX \`category_products_productId_idx\` ON \`category_products\``);
        await queryRunner.query(`DROP INDEX \`cart_product_option_values_cartProductId_idx\` ON \`cart_product_option_values\``);
        await queryRunner.query(`DROP INDEX \`cart_product_option_values_optionValueId_idx\` ON \`cart_product_option_values\``);
        await queryRunner.query(`DROP INDEX \`blog_tag_posts_blogPostId_idx\` ON \`blog_tag_posts\``);
        await queryRunner.query(`DROP INDEX \`blog_tag_posts_blogTagId_idx\` ON \`blog_tag_posts\``);
        await queryRunner.query(`ALTER TABLE \`role\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`role\` CHANGE \`scope\` \`scope\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`option_value\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`option_value\` CHANGE \`optionId\` \`optionId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`option_value\` CHANGE \`productId\` \`productId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`option_value\` CHANGE \`properties\` \`properties\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`option\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`option\` CHANGE \`key\` \`key\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`option\` ADD UNIQUE INDEX \`IDX_e19ad52a146d46abb337f4346f\` (\`key\`)`);
        await queryRunner.query(`ALTER TABLE \`option\` CHANGE \`inFilter\` \`inFilter\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`file\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`file\` CHANGE \`metadata\` \`metadata\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`file\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`file\` CHANGE \`updatedAt\` \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`remoteId\` \`remoteId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`longTitle\` \`longTitle\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`alias\` \`alias\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`category\` ADD UNIQUE INDEX \`IDX_ef133f841a42f39ec1a75b96ce\` (\`alias\`)`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`active\` \`active\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`imageId\` \`imageId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`parentId\` \`parentId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`product_image\` CHANGE \`fileId\` \`fileId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`product_image\` CHANGE \`productId\` \`productId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`product_image\` CHANGE \`active\` \`active\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`offer\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`offer\` CHANGE \`remoteId\` \`remoteId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`offer\` CHANGE \`title\` \`title\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`offer\` CHANGE \`productId\` \`productId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`brand\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`brand\` CHANGE \`remoteId\` \`remoteId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`remoteId\` \`remoteId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`longTitle\` \`longTitle\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`alias\` \`alias\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`product\` ADD UNIQUE INDEX \`IDX_afa492329cc228eb3fdd51d86f\` (\`alias\`)`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`sku\` \`sku\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`priceDecrease\` \`priceDecrease\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`specifications\` \`specifications\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`exploitation\` \`exploitation\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`active\` \`active\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`inStock\` \`inStock\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`recent\` \`recent\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`favorite\` \`favorite\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`brandId\` \`brandId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cart_product\` CHANGE \`productId\` \`productId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`cart_product\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`cart_product\` CHANGE \`updatedAt\` \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`cart\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cart\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`cart\` CHANGE \`updatedAt\` \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`email\` \`email\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD UNIQUE INDEX \`IDX_e12875dfb3b1d92d7d7c5377e2\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`active\` \`active\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`roleId\` \`roleId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`pickup_point\` CHANGE \`phone\` \`phone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pickup_point\` CHANGE \`email\` \`email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pickup_point\` CHANGE \`note\` \`note\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pickup_point\` CHANGE \`isReception\` \`isReception\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`pickup_point\` CHANGE \`isDressingRoom\` \`isDressingRoom\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`pickup_point\` CHANGE \`allowedCod\` \`allowedCod\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`pickup_point\` CHANGE \`haveCash\` \`haveCash\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`pickup_point\` CHANGE \`haveCashless\` \`haveCashless\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`order_product\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`order_product\` CHANGE \`options\` \`options\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`order_product\` CHANGE \`orderId\` \`orderId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`order_product\` CHANGE \`productId\` \`productId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`delivered\` \`delivered\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`recipient\` \`recipient\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`orderId\` \`orderId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`delivery\` ADD UNIQUE INDEX \`IDX_b37d51328f9ca210b573b19372\` (\`orderId\`)`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`deliveredAt\` \`deliveredAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`order\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`order\` CHANGE \`hash\` \`hash\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`order\` ADD UNIQUE INDEX \`IDX_3ed3ed33c81e40c297d9c6f494\` (\`hash\`)`);
        await queryRunner.query(`ALTER TABLE \`order\` CHANGE \`composition\` \`composition\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`order\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`order\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`payment\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`payment\` CHANGE \`paid\` \`paid\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`payment\` CHANGE \`link\` \`link\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payment\` CHANGE \`remoteId\` \`remoteId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payment\` CHANGE \`orderId\` \`orderId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`payment\` ADD UNIQUE INDEX \`IDX_d09d285fe1645cd2f0db811e29\` (\`orderId\`)`);
        await queryRunner.query(`ALTER TABLE \`payment\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`payment\` CHANGE \`paidAt\` \`paidAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_tag\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`blog_tag\` CHANGE \`alias\` \`alias\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_tag\` ADD UNIQUE INDEX \`IDX_4e1e2c9b325cc91218352d344c\` (\`alias\`)`);
        await queryRunner.query(`ALTER TABLE \`blog_tag\` CHANGE \`metadata\` \`metadata\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_post\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`blog_post\` CHANGE \`longTitle\` \`longTitle\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_post\` CHANGE \`alias\` \`alias\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_post\` ADD UNIQUE INDEX \`IDX_b8f6b9a665993b1b4b7abf7cda\` (\`alias\`)`);
        await queryRunner.query(`ALTER TABLE \`blog_post\` CHANGE \`content\` \`content\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_post\` CHANGE \`readTime\` \`readTime\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_post\` CHANGE \`metadata\` \`metadata\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_post\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`blog_post\` CHANGE \`updatedAt\` \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`blog_post\` CHANGE \`imageId\` \`imageId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`category_options\` CHANGE \`optionId\` \`optionId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`category_options\` CHANGE \`categoryId\` \`categoryId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`offer_option_values\` CHANGE \`offerId\` \`offerId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`offer_option_values\` CHANGE \`optionValueId\` \`optionValueId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`category_products\` CHANGE \`productId\` \`productId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`category_products\` CHANGE \`categoryId\` \`categoryId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`cart_product_option_values\` CHANGE \`optionValueId\` \`optionValueId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_tag_posts\` CHANGE \`blogPostId\` \`blogPostId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_tag_posts\` CHANGE \`blogTagId\` \`blogTagId\` int NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_b37d51328f9ca210b573b19372\` ON \`delivery\` (\`orderId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_d09d285fe1645cd2f0db811e29\` ON \`payment\` (\`orderId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_9e1ba3238b73eace1889b218ea\` ON \`category_options\` (\`optionId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_2f594ec911a46edd506101154b\` ON \`category_options\` (\`categoryId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_bc3752c2099f512f94a3b9aa99\` ON \`offer_option_values\` (\`offerId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_6602b912631112245b7e7f638a\` ON \`offer_option_values\` (\`optionValueId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_49783865a1f6736be7f2854dd2\` ON \`category_products\` (\`productId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_c46314c39c804b52464e094620\` ON \`category_products\` (\`categoryId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_375ef969daa02792d687e9bd59\` ON \`cart_product_option_values\` (\`cartProductId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_c57cac20e52a815b03b59ad79f\` ON \`cart_product_option_values\` (\`optionValueId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_8ab783ed0df9d020ffaa3bb558\` ON \`blog_tag_posts\` (\`blogPostId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_a8098dce830e03bc1230b3c6c3\` ON \`blog_tag_posts\` (\`blogTagId\`)`);
        await queryRunner.query(`ALTER TABLE \`option_value\` ADD CONSTRAINT \`FK_2d7616b884ef55e6eb5af000f1d\` FOREIGN KEY (\`optionId\`) REFERENCES \`option\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`option_value\` ADD CONSTRAINT \`FK_15f11407cf576587fa1f6a36b39\` FOREIGN KEY (\`productId\`) REFERENCES \`product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`category\` ADD CONSTRAINT \`FK_8a12e4cb68bc526f8d8e59efb12\` FOREIGN KEY (\`imageId\`) REFERENCES \`file\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`category\` ADD CONSTRAINT \`FK_d5456fd7e4c4866fec8ada1fa10\` FOREIGN KEY (\`parentId\`) REFERENCES \`category\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_image\` ADD CONSTRAINT \`FK_2f757f675fce1f6fdda0cf0ca1f\` FOREIGN KEY (\`fileId\`) REFERENCES \`file\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_image\` ADD CONSTRAINT \`FK_40ca0cd115ef1ff35351bed8da2\` FOREIGN KEY (\`productId\`) REFERENCES \`product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`offer\` ADD CONSTRAINT \`FK_7bb476d64bd0c7abaa62ed62715\` FOREIGN KEY (\`productId\`) REFERENCES \`product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product\` ADD CONSTRAINT \`FK_bb7d3d9dc1fae40293795ae39d6\` FOREIGN KEY (\`brandId\`) REFERENCES \`brand\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_product\` ADD CONSTRAINT \`FK_139f8024067696fe5a8400ebda2\` FOREIGN KEY (\`cartId\`) REFERENCES \`cart\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_product\` ADD CONSTRAINT \`FK_4f1b0c66f4e0b4610e14ca42e5c\` FOREIGN KEY (\`productId\`) REFERENCES \`product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD CONSTRAINT \`FK_c28e52f758e7bbc53828db92194\` FOREIGN KEY (\`roleId\`) REFERENCES \`role\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_product\` ADD CONSTRAINT \`FK_3fb066240db56c9558a91139431\` FOREIGN KEY (\`orderId\`) REFERENCES \`order\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_product\` ADD CONSTRAINT \`FK_073c85ed133e05241040bd70f02\` FOREIGN KEY (\`productId\`) REFERENCES \`product\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`delivery\` ADD CONSTRAINT \`FK_b37d51328f9ca210b573b19372c\` FOREIGN KEY (\`orderId\`) REFERENCES \`order\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order\` ADD CONSTRAINT \`FK_caabe91507b3379c7ba73637b84\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment\` ADD CONSTRAINT \`FK_d09d285fe1645cd2f0db811e293\` FOREIGN KEY (\`orderId\`) REFERENCES \`order\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`blog_post\` ADD CONSTRAINT \`FK_fb86aba3b3fdb50278131d3e325\` FOREIGN KEY (\`imageId\`) REFERENCES \`file\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`category_options\` ADD CONSTRAINT \`FK_9e1ba3238b73eace1889b218eac\` FOREIGN KEY (\`optionId\`) REFERENCES \`option\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`category_options\` ADD CONSTRAINT \`FK_2f594ec911a46edd506101154bf\` FOREIGN KEY (\`categoryId\`) REFERENCES \`category\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`offer_option_values\` ADD CONSTRAINT \`FK_bc3752c2099f512f94a3b9aa99d\` FOREIGN KEY (\`offerId\`) REFERENCES \`offer\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`offer_option_values\` ADD CONSTRAINT \`FK_6602b912631112245b7e7f638a8\` FOREIGN KEY (\`optionValueId\`) REFERENCES \`option_value\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`category_products\` ADD CONSTRAINT \`FK_49783865a1f6736be7f2854dd21\` FOREIGN KEY (\`productId\`) REFERENCES \`product\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`category_products\` ADD CONSTRAINT \`FK_c46314c39c804b52464e0946201\` FOREIGN KEY (\`categoryId\`) REFERENCES \`category\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_product_option_values\` ADD CONSTRAINT \`FK_375ef969daa02792d687e9bd59c\` FOREIGN KEY (\`cartProductId\`) REFERENCES \`cart_product\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`cart_product_option_values\` ADD CONSTRAINT \`FK_c57cac20e52a815b03b59ad79f7\` FOREIGN KEY (\`optionValueId\`) REFERENCES \`option_value\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`blog_tag_posts\` ADD CONSTRAINT \`FK_8ab783ed0df9d020ffaa3bb558a\` FOREIGN KEY (\`blogPostId\`) REFERENCES \`blog_post\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`blog_tag_posts\` ADD CONSTRAINT \`FK_a8098dce830e03bc1230b3c6c3a\` FOREIGN KEY (\`blogTagId\`) REFERENCES \`blog_tag\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`blog_tag_posts\` DROP FOREIGN KEY \`FK_a8098dce830e03bc1230b3c6c3a\``);
        await queryRunner.query(`ALTER TABLE \`blog_tag_posts\` DROP FOREIGN KEY \`FK_8ab783ed0df9d020ffaa3bb558a\``);
        await queryRunner.query(`ALTER TABLE \`cart_product_option_values\` DROP FOREIGN KEY \`FK_c57cac20e52a815b03b59ad79f7\``);
        await queryRunner.query(`ALTER TABLE \`cart_product_option_values\` DROP FOREIGN KEY \`FK_375ef969daa02792d687e9bd59c\``);
        await queryRunner.query(`ALTER TABLE \`category_products\` DROP FOREIGN KEY \`FK_c46314c39c804b52464e0946201\``);
        await queryRunner.query(`ALTER TABLE \`category_products\` DROP FOREIGN KEY \`FK_49783865a1f6736be7f2854dd21\``);
        await queryRunner.query(`ALTER TABLE \`offer_option_values\` DROP FOREIGN KEY \`FK_6602b912631112245b7e7f638a8\``);
        await queryRunner.query(`ALTER TABLE \`offer_option_values\` DROP FOREIGN KEY \`FK_bc3752c2099f512f94a3b9aa99d\``);
        await queryRunner.query(`ALTER TABLE \`category_options\` DROP FOREIGN KEY \`FK_2f594ec911a46edd506101154bf\``);
        await queryRunner.query(`ALTER TABLE \`category_options\` DROP FOREIGN KEY \`FK_9e1ba3238b73eace1889b218eac\``);
        await queryRunner.query(`ALTER TABLE \`blog_post\` DROP FOREIGN KEY \`FK_fb86aba3b3fdb50278131d3e325\``);
        await queryRunner.query(`ALTER TABLE \`payment\` DROP FOREIGN KEY \`FK_d09d285fe1645cd2f0db811e293\``);
        await queryRunner.query(`ALTER TABLE \`order\` DROP FOREIGN KEY \`FK_caabe91507b3379c7ba73637b84\``);
        await queryRunner.query(`ALTER TABLE \`delivery\` DROP FOREIGN KEY \`FK_b37d51328f9ca210b573b19372c\``);
        await queryRunner.query(`ALTER TABLE \`order_product\` DROP FOREIGN KEY \`FK_073c85ed133e05241040bd70f02\``);
        await queryRunner.query(`ALTER TABLE \`order_product\` DROP FOREIGN KEY \`FK_3fb066240db56c9558a91139431\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP FOREIGN KEY \`FK_c28e52f758e7bbc53828db92194\``);
        await queryRunner.query(`ALTER TABLE \`cart_product\` DROP FOREIGN KEY \`FK_4f1b0c66f4e0b4610e14ca42e5c\``);
        await queryRunner.query(`ALTER TABLE \`cart_product\` DROP FOREIGN KEY \`FK_139f8024067696fe5a8400ebda2\``);
        await queryRunner.query(`ALTER TABLE \`product\` DROP FOREIGN KEY \`FK_bb7d3d9dc1fae40293795ae39d6\``);
        await queryRunner.query(`ALTER TABLE \`offer\` DROP FOREIGN KEY \`FK_7bb476d64bd0c7abaa62ed62715\``);
        await queryRunner.query(`ALTER TABLE \`product_image\` DROP FOREIGN KEY \`FK_40ca0cd115ef1ff35351bed8da2\``);
        await queryRunner.query(`ALTER TABLE \`product_image\` DROP FOREIGN KEY \`FK_2f757f675fce1f6fdda0cf0ca1f\``);
        await queryRunner.query(`ALTER TABLE \`category\` DROP FOREIGN KEY \`FK_d5456fd7e4c4866fec8ada1fa10\``);
        await queryRunner.query(`ALTER TABLE \`category\` DROP FOREIGN KEY \`FK_8a12e4cb68bc526f8d8e59efb12\``);
        await queryRunner.query(`ALTER TABLE \`option_value\` DROP FOREIGN KEY \`FK_15f11407cf576587fa1f6a36b39\``);
        await queryRunner.query(`ALTER TABLE \`option_value\` DROP FOREIGN KEY \`FK_2d7616b884ef55e6eb5af000f1d\``);
        await queryRunner.query(`DROP INDEX \`IDX_a8098dce830e03bc1230b3c6c3\` ON \`blog_tag_posts\``);
        await queryRunner.query(`DROP INDEX \`IDX_8ab783ed0df9d020ffaa3bb558\` ON \`blog_tag_posts\``);
        await queryRunner.query(`DROP INDEX \`IDX_c57cac20e52a815b03b59ad79f\` ON \`cart_product_option_values\``);
        await queryRunner.query(`DROP INDEX \`IDX_375ef969daa02792d687e9bd59\` ON \`cart_product_option_values\``);
        await queryRunner.query(`DROP INDEX \`IDX_c46314c39c804b52464e094620\` ON \`category_products\``);
        await queryRunner.query(`DROP INDEX \`IDX_49783865a1f6736be7f2854dd2\` ON \`category_products\``);
        await queryRunner.query(`DROP INDEX \`IDX_6602b912631112245b7e7f638a\` ON \`offer_option_values\``);
        await queryRunner.query(`DROP INDEX \`IDX_bc3752c2099f512f94a3b9aa99\` ON \`offer_option_values\``);
        await queryRunner.query(`DROP INDEX \`IDX_2f594ec911a46edd506101154b\` ON \`category_options\``);
        await queryRunner.query(`DROP INDEX \`IDX_9e1ba3238b73eace1889b218ea\` ON \`category_options\``);
        await queryRunner.query(`DROP INDEX \`REL_d09d285fe1645cd2f0db811e29\` ON \`payment\``);
        await queryRunner.query(`DROP INDEX \`REL_b37d51328f9ca210b573b19372\` ON \`delivery\``);
        await queryRunner.query(`ALTER TABLE \`blog_tag_posts\` CHANGE \`blogTagId\` \`blogTagId\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_tag_posts\` CHANGE \`blogPostId\` \`blogPostId\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`cart_product_option_values\` CHANGE \`optionValueId\` \`optionValueId\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`category_products\` CHANGE \`categoryId\` \`categoryId\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`category_products\` CHANGE \`productId\` \`productId\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`offer_option_values\` CHANGE \`optionValueId\` \`optionValueId\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`offer_option_values\` CHANGE \`offerId\` \`offerId\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`category_options\` CHANGE \`categoryId\` \`categoryId\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`category_options\` CHANGE \`optionId\` \`optionId\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_post\` CHANGE \`imageId\` \`imageId\` int UNSIGNED NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`blog_post\` CHANGE \`updatedAt\` \`updatedAt\` datetime(3) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_post\` CHANGE \`createdAt\` \`createdAt\` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE \`blog_post\` CHANGE \`metadata\` \`metadata\` text COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`blog_post\` CHANGE \`readTime\` \`readTime\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`blog_post\` CHANGE \`content\` \`content\` text COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`blog_post\` DROP INDEX \`IDX_b8f6b9a665993b1b4b7abf7cda\``);
        await queryRunner.query(`ALTER TABLE \`blog_post\` CHANGE \`alias\` \`alias\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_post\` CHANGE \`longTitle\` \`longTitle\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`blog_post\` CHANGE \`id\` \`id\` int UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`blog_tag\` CHANGE \`metadata\` \`metadata\` text COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`blog_tag\` DROP INDEX \`IDX_4e1e2c9b325cc91218352d344c\``);
        await queryRunner.query(`ALTER TABLE \`blog_tag\` CHANGE \`alias\` \`alias\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_tag\` CHANGE \`id\` \`id\` int UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`payment\` CHANGE \`paidAt\` \`paidAt\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payment\` CHANGE \`createdAt\` \`createdAt\` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE \`payment\` DROP INDEX \`IDX_d09d285fe1645cd2f0db811e29\``);
        await queryRunner.query(`ALTER TABLE \`payment\` CHANGE \`orderId\` \`orderId\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`payment\` CHANGE \`remoteId\` \`remoteId\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payment\` CHANGE \`link\` \`link\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payment\` CHANGE \`paid\` \`paid\` tinyint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payment\` CHANGE \`id\` \`id\` int UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`order\` CHANGE \`userId\` \`userId\` int UNSIGNED NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order\` CHANGE \`createdAt\` \`createdAt\` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE \`order\` CHANGE \`composition\` \`composition\` text COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order\` DROP INDEX \`IDX_3ed3ed33c81e40c297d9c6f494\``);
        await queryRunner.query(`ALTER TABLE \`order\` CHANGE \`hash\` \`hash\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`order\` CHANGE \`id\` \`id\` int UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`deliveredAt\` \`deliveredAt\` datetime(3) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`createdAt\` \`createdAt\` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE \`delivery\` DROP INDEX \`IDX_b37d51328f9ca210b573b19372\``);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`orderId\` \`orderId\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`recipient\` \`recipient\` text COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`delivered\` \`delivered\` tinyint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`id\` \`id\` int UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`order_product\` CHANGE \`productId\` \`productId\` int UNSIGNED NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_product\` CHANGE \`orderId\` \`orderId\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`order_product\` CHANGE \`options\` \`options\` text COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_product\` CHANGE \`id\` \`id\` int UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`pickup_point\` CHANGE \`haveCashless\` \`haveCashless\` tinyint(1) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`pickup_point\` CHANGE \`haveCash\` \`haveCash\` tinyint(1) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`pickup_point\` CHANGE \`allowedCod\` \`allowedCod\` tinyint(1) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`pickup_point\` CHANGE \`isDressingRoom\` \`isDressingRoom\` tinyint(1) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`pickup_point\` CHANGE \`isReception\` \`isReception\` tinyint(1) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`pickup_point\` CHANGE \`note\` \`note\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pickup_point\` CHANGE \`email\` \`email\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pickup_point\` CHANGE \`phone\` \`phone\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`roleId\` \`roleId\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`active\` \`active\` tinyint(1) NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP INDEX \`IDX_e12875dfb3b1d92d7d7c5377e2\``);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`email\` \`email\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`id\` \`id\` int UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`cart\` CHANGE \`updatedAt\` \`updatedAt\` datetime(3) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`cart\` CHANGE \`createdAt\` \`createdAt\` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE \`cart\` CHANGE \`userId\` \`userId\` int UNSIGNED NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cart_product\` CHANGE \`updatedAt\` \`updatedAt\` datetime(3) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`cart_product\` CHANGE \`createdAt\` \`createdAt\` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE \`cart_product\` CHANGE \`productId\` \`productId\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`brandId\` \`brandId\` int UNSIGNED NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`favorite\` \`favorite\` tinyint(1) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`recent\` \`recent\` tinyint(1) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`inStock\` \`inStock\` tinyint(1) NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`active\` \`active\` tinyint(1) NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`exploitation\` \`exploitation\` text COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`specifications\` \`specifications\` text COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`description\` \`description\` text COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`priceDecrease\` \`priceDecrease\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`sku\` \`sku\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product\` DROP INDEX \`IDX_afa492329cc228eb3fdd51d86f\``);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`alias\` \`alias\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`longTitle\` \`longTitle\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`remoteId\` \`remoteId\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`id\` \`id\` int UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`brand\` CHANGE \`remoteId\` \`remoteId\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`brand\` CHANGE \`id\` \`id\` int UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`offer\` CHANGE \`productId\` \`productId\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`offer\` CHANGE \`title\` \`title\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`offer\` CHANGE \`remoteId\` \`remoteId\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`offer\` CHANGE \`id\` \`id\` int UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`product_image\` CHANGE \`active\` \`active\` tinyint(1) NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`product_image\` CHANGE \`productId\` \`productId\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`product_image\` CHANGE \`fileId\` \`fileId\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`parentId\` \`parentId\` int UNSIGNED NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`imageId\` \`imageId\` int UNSIGNED NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`active\` \`active\` tinyint(1) NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`description\` \`description\` text COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`category\` DROP INDEX \`IDX_ef133f841a42f39ec1a75b96ce\``);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`alias\` \`alias\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`longTitle\` \`longTitle\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`remoteId\` \`remoteId\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`id\` \`id\` int UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`file\` CHANGE \`updatedAt\` \`updatedAt\` datetime(3) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`file\` CHANGE \`createdAt\` \`createdAt\` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE \`file\` CHANGE \`metadata\` \`metadata\` text COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`file\` CHANGE \`id\` \`id\` int UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`option\` CHANGE \`inFilter\` \`inFilter\` tinyint(1) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`option\` DROP INDEX \`IDX_e19ad52a146d46abb337f4346f\``);
        await queryRunner.query(`ALTER TABLE \`option\` CHANGE \`key\` \`key\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`option\` CHANGE \`id\` \`id\` int UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`option_value\` CHANGE \`properties\` \`properties\` text COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`option_value\` CHANGE \`productId\` \`productId\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`option_value\` CHANGE \`optionId\` \`optionId\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`option_value\` CHANGE \`id\` \`id\` int UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`role\` CHANGE \`scope\` \`scope\` text COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`role\` CHANGE \`id\` \`id\` int UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`CREATE INDEX \`blog_tag_posts_blogTagId_idx\` ON \`blog_tag_posts\` (\`blogTagId\`)`);
        await queryRunner.query(`CREATE INDEX \`blog_tag_posts_blogPostId_idx\` ON \`blog_tag_posts\` (\`blogPostId\`)`);
        await queryRunner.query(`CREATE INDEX \`cart_product_option_values_optionValueId_idx\` ON \`cart_product_option_values\` (\`optionValueId\`)`);
        await queryRunner.query(`CREATE INDEX \`cart_product_option_values_cartProductId_idx\` ON \`cart_product_option_values\` (\`cartProductId\`)`);
        await queryRunner.query(`CREATE INDEX \`category_products_productId_idx\` ON \`category_products\` (\`productId\`)`);
        await queryRunner.query(`CREATE INDEX \`category_products_categoryId_idx\` ON \`category_products\` (\`categoryId\`)`);
        await queryRunner.query(`CREATE INDEX \`offer_option_values_optionValueId_idx\` ON \`offer_option_values\` (\`optionValueId\`)`);
        await queryRunner.query(`CREATE INDEX \`offer_option_values_offerId_idx\` ON \`offer_option_values\` (\`offerId\`)`);
        await queryRunner.query(`CREATE INDEX \`category_options_optionId_idx\` ON \`category_options\` (\`optionId\`)`);
        await queryRunner.query(`CREATE INDEX \`category_options_categoryId_idx\` ON \`category_options\` (\`categoryId\`)`);
        await queryRunner.query(`CREATE INDEX \`blog_post_imageId_idx\` ON \`blog_post\` (\`imageId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`blog_post_alias_key\` ON \`blog_post\` (\`alias\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`blog_tag_alias_key\` ON \`blog_tag\` (\`alias\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`payment_orderId_key\` ON \`payment\` (\`orderId\`)`);
        await queryRunner.query(`CREATE INDEX \`order_userId_idx\` ON \`order\` (\`userId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`order_hash_key\` ON \`order\` (\`hash\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`delivery_orderId_key\` ON \`delivery\` (\`orderId\`)`);
        await queryRunner.query(`CREATE INDEX \`order_product_productId_idx\` ON \`order_product\` (\`productId\`)`);
        await queryRunner.query(`CREATE INDEX \`order_product_orderId_idx\` ON \`order_product\` (\`orderId\`)`);
        await queryRunner.query(`CREATE INDEX \`user_roleId_idx\` ON \`user\` (\`roleId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`user_email_key\` ON \`user\` (\`email\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`cart_userId_key\` ON \`cart\` (\`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`cart_product_productId_idx\` ON \`cart_product\` (\`productId\`)`);
        await queryRunner.query(`CREATE INDEX \`cart_product_cartId_idx\` ON \`cart_product\` (\`cartId\`)`);
        await queryRunner.query(`CREATE INDEX \`product_brandId_idx\` ON \`product\` (\`brandId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`product_alias_key\` ON \`product\` (\`alias\`)`);
        await queryRunner.query(`CREATE INDEX \`offer_productId_idx\` ON \`offer\` (\`productId\`)`);
        await queryRunner.query(`CREATE INDEX \`product_image_productId_idx\` ON \`product_image\` (\`productId\`)`);
        await queryRunner.query(`CREATE INDEX \`product_image_fileId_idx\` ON \`product_image\` (\`fileId\`)`);
        await queryRunner.query(`CREATE INDEX \`category_parentId_idx\` ON \`category\` (\`parentId\`)`);
        await queryRunner.query(`CREATE INDEX \`category_imageId_idx\` ON \`category\` (\`imageId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`category_alias_key\` ON \`category\` (\`alias\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`option_key_key\` ON \`option\` (\`key\`)`);
        await queryRunner.query(`CREATE INDEX \`option_value_productId_idx\` ON \`option_value\` (\`productId\`)`);
        await queryRunner.query(`CREATE INDEX \`option_value_optionId_idx\` ON \`option_value\` (\`optionId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`role_title_key\` ON \`role\` (\`title\`)`);
        await queryRunner.query(`ALTER TABLE \`blog_tag_posts\` ADD CONSTRAINT \`blog_tag_posts_blogTagId_fkey\` FOREIGN KEY (\`blogTagId\`) REFERENCES \`blog_tag\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`blog_tag_posts\` ADD CONSTRAINT \`blog_tag_posts_blogPostId_fkey\` FOREIGN KEY (\`blogPostId\`) REFERENCES \`blog_post\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`cart_product_option_values\` ADD CONSTRAINT \`cart_product_option_values_optionValueId_fkey\` FOREIGN KEY (\`optionValueId\`) REFERENCES \`option_value\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`cart_product_option_values\` ADD CONSTRAINT \`cart_product_option_values_cartProductId_fkey\` FOREIGN KEY (\`cartProductId\`) REFERENCES \`cart_product\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`category_products\` ADD CONSTRAINT \`category_products_productId_fkey\` FOREIGN KEY (\`productId\`) REFERENCES \`product\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`category_products\` ADD CONSTRAINT \`category_products_categoryId_fkey\` FOREIGN KEY (\`categoryId\`) REFERENCES \`category\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`offer_option_values\` ADD CONSTRAINT \`offer_option_values_optionValueId_fkey\` FOREIGN KEY (\`optionValueId\`) REFERENCES \`option_value\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`offer_option_values\` ADD CONSTRAINT \`offer_option_values_offerId_fkey\` FOREIGN KEY (\`offerId\`) REFERENCES \`offer\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`category_options\` ADD CONSTRAINT \`category_options_optionId_fkey\` FOREIGN KEY (\`optionId\`) REFERENCES \`option\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`category_options\` ADD CONSTRAINT \`category_options_categoryId_fkey\` FOREIGN KEY (\`categoryId\`) REFERENCES \`category\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`blog_post\` ADD CONSTRAINT \`blog_post_imageId_fkey\` FOREIGN KEY (\`imageId\`) REFERENCES \`file\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`payment\` ADD CONSTRAINT \`payment_orderId_fkey\` FOREIGN KEY (\`orderId\`) REFERENCES \`order\`(\`id\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`order\` ADD CONSTRAINT \`order_userId_fkey\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`delivery\` ADD CONSTRAINT \`delivery_orderId_fkey\` FOREIGN KEY (\`orderId\`) REFERENCES \`order\`(\`id\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`order_product\` ADD CONSTRAINT \`order_product_productId_fkey\` FOREIGN KEY (\`productId\`) REFERENCES \`product\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`order_product\` ADD CONSTRAINT \`order_product_orderId_fkey\` FOREIGN KEY (\`orderId\`) REFERENCES \`order\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD CONSTRAINT \`user_roleId_fkey\` FOREIGN KEY (\`roleId\`) REFERENCES \`role\`(\`id\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`cart\` ADD CONSTRAINT \`cart_userId_fkey\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`cart_product\` ADD CONSTRAINT \`cart_product_productId_fkey\` FOREIGN KEY (\`productId\`) REFERENCES \`product\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`cart_product\` ADD CONSTRAINT \`cart_product_cartId_fkey\` FOREIGN KEY (\`cartId\`) REFERENCES \`cart\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`product\` ADD CONSTRAINT \`product_brandId_fkey\` FOREIGN KEY (\`brandId\`) REFERENCES \`brand\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`offer\` ADD CONSTRAINT \`offer_productId_fkey\` FOREIGN KEY (\`productId\`) REFERENCES \`product\`(\`id\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`product_image\` ADD CONSTRAINT \`product_image_productId_fkey\` FOREIGN KEY (\`productId\`) REFERENCES \`product\`(\`id\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`product_image\` ADD CONSTRAINT \`product_image_fileId_fkey\` FOREIGN KEY (\`fileId\`) REFERENCES \`file\`(\`id\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`category\` ADD CONSTRAINT \`category_parentId_fkey\` FOREIGN KEY (\`parentId\`) REFERENCES \`category\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`category\` ADD CONSTRAINT \`category_imageId_fkey\` FOREIGN KEY (\`imageId\`) REFERENCES \`file\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`option_value\` ADD CONSTRAINT \`option_value_productId_fkey\` FOREIGN KEY (\`productId\`) REFERENCES \`product\`(\`id\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`option_value\` ADD CONSTRAINT \`option_value_optionId_fkey\` FOREIGN KEY (\`optionId\`) REFERENCES \`option\`(\`id\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
    }

}
