export const byDirection = [
  {
    title: 'Всё для подводной охоты',
    items: [
      { title: 'Гидрокостюмы', href: '#Гидрокостюмы' },
      { title: 'Ласты для подводной охоты', href: '#Ласты для подводной охоты' },
      { title: 'Ружья Пневматы', href: '#Ружья Пневматы' },
      { title: 'Маски', href: '#Маски' },
      { title: 'Трубки', href: '#Трубки' },
      { title: 'Запчасти для ласт', href: '#Запчасти для ласт' },
      { title: 'Пояса и пряжки', href: '#Пояса и пряжки' },
      { title: 'Химия', href: '#Химия' },
      { title: 'Фонари', href: '#Фонари' },
      { title: 'Сумки, чехлы, боксы', href: '#Сумки, чехлы, боксы' },
      { title: 'Слинги', href: '#Слинги' },
      { title: 'Ремонт ружей пневматы', href: '#Ремонт ружей пневматы' },
      { title: 'Перчатки', href: '#Перчатки' },
      { title: 'Носки', href: '#Носки' },
      { title: 'Ножи', href: '#Ножи' },
      { title: 'Неопреновые аксессуары', href: '#Неопреновые аксессуары' },
      { title: 'Наконечники', href: '#Наконечники' },
      { title: 'Линь', href: '#Линь' },
      { title: 'Куканы', href: '#Куканы' },
      { title: 'Катушки', href: '#Катушки' },
      { title: 'Груза и грузовые системы', href: '#Груза и грузовые системы' },
      { title: 'Гарпуны', href: '#Гарпуны' },
      { title: 'Буи, буксировщики, плоты', href: '#Буи, буксировщики, плоты' },
      { title: 'Арбалеты', href: '#Арбалеты' },
      { title: 'Ремонт арбалета', href: '#Ремонт арбалета' },
      { title: 'Акссесуары для фонарей', href: '#Акссесуары для фонарей' },
      { title: 'Аксессуары для ружей пневматы', href: '#Аксессуары для ружей пневматы' },
      { title: 'Аксессуары для подводной охоты', href: '#Аксессуары для подводной охоты' },
      { title: 'Разгрузочные жилеты', href: '#Разгрузочные жилеты' },
      { title: 'Компьютеры для подводной охоты', href: '#Компьютеры для подводной охоты' },
      { title: 'Акссесуары для арбалета', href: '#Акссесуары для арбалета' },
      { title: 'Тяги для арбалета', href: '#Тяги для арбалета' }
    ]
  },
  {
    title: 'Всё для дайвинга',
    items: [
      { title: 'Шланги', href: '#Шланги' },
      { title: 'Шлемы', href: '#Шлемы' },
      {
        title: 'Гидрокостюмы для дайвинга и сёрфинга',
        href: '#Гидрокостюмы для дайвинга и сёрфинга'
      },
      { title: 'Ласты для дайвинга', href: '#Ласты для дайвинга' },
      { title: 'Баллоны для дайвинга', href: '#Баллоны для дайвинга' },
      { title: 'Маски', href: '#Маски' },
      { title: 'Трубки', href: '#Трубки' },
      { title: 'Компенсаторы', href: '#Компенсаторы' },
      { title: 'Приборы и компьютеры', href: '#Приборы и компьютеры' },
      { title: 'Аксессуары для ласт', href: '#Аксессуары для ласт' },
      { title: 'Аксессуары для дайвинга', href: '#Аксессуары для дайвинга' },
      { title: 'Аксессуары для фото и видеосъёмки', href: '#Аксессуары для фото и видеосъёмки' },
      { title: 'Регуляторы и октопусы', href: '#Регуляторы и октопусы' },
      { title: 'Боты', href: '#Боты' },
      { title: 'Химия', href: '#Химия' },
      { title: 'Фонари', href: '#Фонари' },
      { title: 'Сумки, чехлы, боксы', href: '#Сумки, чехлы, боксы' },
      { title: 'Пояса и пряжки', href: '#Пояса и пряжки' },
      { title: 'Перчатки', href: '#Перчатки' },
      { title: 'Носки', href: '#Носки' },
      { title: 'Ножи', href: '#Ножи' },
      { title: 'Неопреновые аксессуары', href: '#Неопреновые аксессуары' },
      { title: 'Груза и грузовые системы', href: '#Груза и грузовые системы' },
      { title: 'Буи, буксировщики, плоты', href: '#Буи, буксировщики, плоты' },
      { title: 'Аксессуары для фонарей', href: '#Аксессуары для фонарей' }
    ]
  },
  {
    title: 'Все для плавания',
    href: '#test',
    items: []
  },
  {
    title: 'Бренды',
    items: [
      { title: 'SARGAN', href: '#SARGAN' },
      { title: 'SALVIMAR', href: '#SALVIMAR' },
      { title: 'OMER', href: '#OMER' },
      { title: 'AQUADISCOVERY', href: '#AQUADISCOVERY' },
      { title: 'CRESSI', href: '#CRESSI' },
      { title: 'IMERSION', href: '#IMERSION' },
      { title: 'BS DIVER', href: '#BS DIVER' },
      { title: 'AKVILON', href: '#AKVILON' },
      { title: 'FEREI', href: '#FEREI' },
      { title: 'PELENGAS', href: '#PELENGAS' },
      { title: 'SEAC SUB', href: '#SEAC SUB' },
      { title: 'DIVEMASTER', href: '#DIVEMASTER' },
      { title: 'PICASSO', href: '#PICASSO' },
      { title: 'ТАЙМЕНЬ', href: '#ТАЙМЕНЬ' },
      { title: 'MARES', href: '#MARES' },
      { title: 'SCORPENA', href: '#SCORPENA' },
      { title: 'IST', href: '#IST' },
      { title: 'АТАКА', href: '#АТАКА' },
      { title: 'AQUALUNG', href: '#AQUALUNG' },
      { title: 'BEUCHAT', href: '#BEUCHAT' },
      { title: 'LITOKALA', href: '#LITOKALA' },
      { title: 'C-4', href: '#C-4' },
      { title: 'SAEKO', href: '#SAEKO' },
      { title: 'JAKBOENO', href: '#JAKBOENO' },
      { title: 'SUUNTO', href: '#SUUNTO' },
      { title: 'XIAOMI', href: '#XIAOMI' },
      { title: 'BATIAL', href: '#BATIAL' },
      { title: 'Guul', href: '#Guul' },
      { title: 'YAKAYASUB', href: '#YAKAYASUB' },
      { title: 'ПМЗ', href: '#ПМЗ' },
      { title: 'DEMKA', href: '#DEMKA' },
      { title: 'SPEARFISHING', href: '#SPEARFISHING' },
      { title: 'LEADERFINS', href: '#LEADERFINS' },
      { title: 'AQUATEAM', href: '#AQUATEAM' },
      { title: 'RIFFE', href: '#RIFFE' },
      { title: 'SPETTON', href: '#SPETTON' },
      { title: 'AOFAR', href: '#AOFAR' },
      { title: 'ДЕЛЬФИН', href: '#ДЕЛЬФИН' },
      { title: 'TUSA', href: '#TUSA' },
      { title: 'PANASONIC', href: '#PANASONIC' },
      { title: 'SCUBAPRO', href: '#SCUBAPRO' },
      { title: 'MARLIN', href: '#MARLIN' },
      { title: 'WATERPROOF', href: '#WATERPROOF' },
      { title: 'GoPro', href: '#GoPro' },
      { title: 'ZELINKA', href: '#ZELINKA' }
    ]
  }
]
