ARG PHP_VERSION

FROM php:${PHP_VERSION}-fpm
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

RUN apt update
RUN apt-get install -y zlib1g-dev libzip-dev libpng-dev libwebp-dev libjpeg62-turbo-dev zip unzip bash cron

RUN ln -sf /bin/bash /bin/sh

RUN docker-php-ext-configure gd --with-jpeg --with-webp && docker-php-ext-install gd
RUN docker-php-ext-install exif
RUN docker-php-ext-install zip
RUN docker-php-ext-install pdo_mysql

ARG TZ
RUN echo "date.timezone=${TZ}" > /usr/local/etc/php/conf.d/docker-php-ext-timezone.ini
RUN echo "memory_limit=512M" > /usr/local/etc/php/conf.d/docker-php-ext-memory.ini
RUN echo "max_file_uploads=256M" > /usr/local/etc/php/conf.d/docker-php-ext-upload.ini \
  && echo "post_max_size=256M" >> /usr/local/etc/php/conf.d/docker-php-ext-upload.ini \
  && echo "upload_max_filesize=256M" >> /usr/local/etc/php/conf.d/docker-php-ext-upload.ini

RUN echo "* * * * * www-data /usr/local/bin/php /vesp/core/cli/cron.php" >> /etc/crontab

ARG PHP_XDEBUG
RUN if [ "$PHP_XDEBUG" = "1" ]; then \
      yes | pecl install xdebug-3.3.0 \
          && echo "zend_extension=xdebug" > /usr/local/etc/php/conf.d/xdebug.ini \
          && echo "xdebug.mode=develop,debug" >> /usr/local/etc/php/conf.d/xdebug.ini \
          && echo "xdebug.client_host=host.docker.internal" >> /usr/local/etc/php/conf.d/xdebug.ini \
          && echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/xdebug.ini \
          && echo "xdebug.idekey=PHPSTORM" >> /usr/local/etc/php/conf.d/xdebug.ini \
          && echo "xdebug.log_level=0" >> /usr/local/etc/php/conf.d/xdebug.ini; \
    fi

ARG UID
ARG GID
ENV UID=${UID}
ENV GID=${GID}
# RUN addgroup --system --gid ${GID} vesp
# RUN adduser --system --gid ${GID} --disabled-password --no-create-home --shell /bin/sh --uid ${UID} vesp
# RUN sed -i "s/user = www-data/user = vesp/g" /usr/local/etc/php-fpm.d/www.conf
# RUN sed -i "s/group = www-data/group = vesp/g" /usr/local/etc/php-fpm.d/www.conf
# RUN usermod -u ${UID} www-data
# RUN groupmod -g ${GID} www-data
RUN sed -i "s/user = www-data/user = root/g" /usr/local/etc/php-fpm.d/www.conf
RUN sed -i "s/group = www-data/group = root/g" /usr/local/etc/php-fpm.d/www.conf